# Generated by Django 4.0.10 on 2024-01-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licopedia.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licopedia.cocktails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licopedia.customuser')),
            ],
        ),
    ]
