# Generated by Django 4.0.10 on 2024-01-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licopedia', '0002_usersession_savedcocktails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktails',
            options={'verbose_name_plural': 'Cocktails'},
        ),
        migrations.AlterModelOptions(
            name='savedcocktails',
            options={'verbose_name_plural': 'Saved Cocktails'},
        ),
    ]
